### PR TITLE
Fix: Works with both classic and block checkout

### PR DESCRIPTION
**Pull request by rossthemusicteacher**
Fixed to work with block checkout as well as classic checkout, previously it only worked with classic checkout.

### CODE REVIEW

**Comment by post-duif** [comment]
> Fixed to work with block checkout as well as classic checkout, previously it only worked with classic checkout.

Thanks for this commit! Will review, merge and push to the WordPress repo within two weeks, busy with things now.

**Comment by rossthemusicteacher** [comment]
Thank you! Very glad you started this project. This integration is going to be huge for ListMonk, Woo, as well as our customers. Happy to continue to contribute.

**Comment by post-duif** [comment]
> Thank you! Very glad you started this project. This integration is going to be huge for ListMonk, Woo, as well as our customers. Happy to continue to contribute.

Glad to hear that, appreciated! Contributions through writing code or buymeacoffee always welcome :)

**Review by post-duif — APPROVED** [review]
Reviewed the code, it's working!

**Pull request merged**
